name: brainvault
description: "BrainVault - Chat with your PDF documents using AI"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  dio: ^5.9.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  file_picker: ^10.3.8
  go_router: ^17.0.1
  shared_preferences: ^2.5.4
  cloud_firestore: ^6.1.1
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.4
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  mocktail: ^1.0.4
  firebase_auth_platform_interface: ^8.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/splash/
    - assets/images/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/app_icon_1024.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#6750A4"
  adaptive_icon_foreground: "assets/images/icons/app_icon_1024.png"

flutter_native_splash:
  color: "#FFFBFE"
  image: "assets/images/splash/logo_splash.png"
  color_dark: "#1C1B1F"
  image_dark: "assets/images/splash/logo_splash.png"
  android: true
  ios: true
  web: false
  android_12:
    image: "assets/images/splash/logo_splash.png"
    icon_background_color: "#FFFBFE"
    image_dark: "assets/images/splash/logo_splash.png"
    icon_background_color_dark: "#1C1B1F"
